name: build-and-test

on: push

jobs:
  test:
    strategy:
      matrix:
        stack_version: [22, 24, 26]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Installation
      run: ./bin/test.sh ${{ matrix.stack_version }}
